-- Remove 59 students that are in database but NOT in provided list
SET session_replication_role = 'origin';

DELETE FROM students WHERE full_name = 'RABIU OLUUMANIFEMI' AND class = 'SS3B/C';
DELETE FROM students WHERE full_name = 'ISIAKA KHADEEJAH' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'AZEEZ ABDUL-MUJEEB' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'AREGBESOLA OLUWASEREMILOR' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'Bankole, Balkis' AND class = 'SS2A4';
DELETE FROM students WHERE full_name = 'SOWUNMI EMMANUEL' AND class = 'J.S.3D';
DELETE FROM students WHERE full_name = 'UBIJI-PRINCE MICHAEL' AND class = 'JSS3C';
DELETE FROM students WHERE full_name = 'OWONIKOKO BALIKIS' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'MORONKOLA MUH AWAL' AND class = 'SS1A3';
DELETE FROM students WHERE full_name = 'BABALOLA ATIOLOLA' AND class = 'SS1B/C';
DELETE FROM students WHERE full_name = 'IBRAHIM ABDELSAMAD' AND class = 'SS2A2';
DELETE FROM students WHERE full_name = 'FAYODA TAMILOR' AND class = 'SS2A3';
DELETE FROM students WHERE full_name = 'MUSTAPHA LOTEFHO' AND class = 'SS2B/C';
DELETE FROM students WHERE full_name = 'ALGERO SOFEYAH' AND class = 'SS2A2';
DELETE FROM students WHERE full_name = 'FAGBOHUN MAYOMIPOS' AND class = 'SS1B/C';
DELETE FROM students WHERE full_name = 'DADA FAREEDAH' AND class = 'SS1B/C';
DELETE FROM students WHERE full_name = 'ARAGUNADE ZAINAB' AND class = 'SS2A2';
DELETE FROM students WHERE full_name = 'OSENKEHINDE' AND class = 'SS2A4';
DELETE FROM students WHERE full_name = 'BANKOLE BALKIS' AND class = 'SS2A4';
DELETE FROM students WHERE full_name = 'OYEBADEN IREDUVIA' AND class = 'SS2A4';
DELETE FROM students WHERE full_name = 'Akinyemi Abdulazeez' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Akinlabi Saheed' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Akintola Abdulmalik' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Kakanfo Michael Eniolay' AND class = 'SS1A3';
DELETE FROM students WHERE full_name = 'Ibrahim Abdulsamad' AND class = 'SS2A2';
DELETE FROM students WHERE full_name = 'Hassan Abdul-Malik' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'AREM FARIDAT' AND class = 'JSS2C';
DELETE FROM students WHERE full_name = 'SALAUDEN KHADEEJAH' AND class = 'JSS2C';
DELETE FROM students WHERE full_name = 'SALAUDEN FRIDA' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'ADEYEO OLUWAGBEMISOLA' AND class = 'JSS3C';
DELETE FROM students WHERE full_name = 'ARIBISALA AYOMIKUN' AND class = 'JSS3C';
DELETE FROM students WHERE full_name = 'ADENUNMI MARK' AND class = 'JSS3D';
DELETE FROM students WHERE full_name = 'Ajbode Nasirudeen' AND class = 'JSS2A';
DELETE FROM students WHERE full_name = 'AKINSOLA TASLEMAH' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'SALAUDEN JUBRIL' AND class = 'SS1A2';
DELETE FROM students WHERE full_name = 'SALAUDEN HALIMAH' AND class = 'SS1A4';
DELETE FROM students WHERE full_name = 'Akinde Aishat' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Akande Taofeeq' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Ajibola Faruq' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Abdulsalam Basit' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Ajadi Aishat' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Afolabi Mariam' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Afolayan Faruq' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Abdulsalam Mutmainah' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Abdulmalik Aisha' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Abubakar Hafsat' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Abdulwasiu Abdulrahman' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Adeniyi Abdulmalik' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Ahmad Abdulmalik' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Akinyemi Abdulwahab' AND class = 'JSS2C';
DELETE FROM students WHERE full_name = 'Afolayan Abdulgafar' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Akinfenwa Taofeek' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Akintunde Abdulgafar' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Akinfenwa Habeeb' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Akinyemi Zainab' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Akintunde Taofeek' AND class = 'JSS2D';
DELETE FROM students WHERE full_name = 'Aina Al-Mubarak' AND class = 'SS2B/C';
DELETE FROM students WHERE full_name = 'Kudeti Abdul-Aleem' AND class = 'SS1A3';
DELETE FROM students WHERE full_name = 'MUSTAPHA ABULLABEEF' AND class = 'SS3A2';
DELETE FROM students WHERE full_name = 'Akintade Rofiat' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Akintunde Habeeb' AND class = 'JSS2B';
DELETE FROM students WHERE full_name = 'Afolayan Muhammed' AND class = 'JSS2C';
DELETE FROM students WHERE full_name = 'Adewale Taofeek' AND class = 'JSS2C';

RESET session_replication_role;
